<a href="https://colab.research.google.com/github/CodeMan-9527/colab/blob/main/helloworld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello colab")

hello colab


# 100 numpy exercises

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [3]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)
`hint: np.__version__, np.show_config)`

In [5]:
print(np.version)
np.show_config()

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openbl

#### 3. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [7]:
np.zeros(10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`hint: size, itemsize`

In [10]:
z = np.zeros((10,10))
print(z.size*z.itemsize)

800


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [12]:
array10 = np.zeros(10)
array10[4] = 1
print(array10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [14]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [16]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

#### 8. Reverse a vector (first element becomes last) (★☆☆)
`hint: array[::-1]`

In [20]:
v = np.arange(10)
vv = v[::-1]
print(v)
print(vv)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
